'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');
const { passwordRecord, makeId, randomHex } = require('./crypto-utils');

const ROOT = path.join(__dirname, '..', '..');
const PLATFORM_DIR = path.join(ROOT, 'platform');
const CLIENTS_DIR = path.join(ROOT, 'clients');

const VENDOR_EMAIL = 'simantovmeir84@gmail.com';
const VENDOR_PASSWORD = '0546464124';

const PERMISSIONS = [
  'dashboard.view', 'networks.manage', 'branches.manage', 'products.manage', 'orders.view',
  'orders.create', 'orders.edit', 'orders.status', 'orders.pack', 'stats.view', 'contacts.manage',
  'delivery.manage', 'users.manage', 'integrations.manage', 'imports.manage'
];

const IGNORE_NAMES = new Set([
  'node_modules', 'dist-desktop', 'dist-installers', 'dist-server', 'data', 'build', '.gradle', 'Pods', '.git', '.env'
]);

function slugify(name) {
  const base = String(name || 'client').trim()
    .replace(/[^\p{L}\p{N}\s-]/gu, '')
    .replace(/\s+/g, '-')
    .toLowerCase();
  return base || 'client';
}

function uniqueFolderName(baseSlug) {
  let candidate = baseSlug;
  let i = 1;
  while (fs.existsSync(path.join(CLIENTS_DIR, candidate))) {
    i += 1;
    candidate = `${baseSlug}-${i}`;
  }
  return candidate;
}

function copyDir(src, dst) {
  if (!fs.existsSync(src)) return;
  const base = path.basename(src);
  if (IGNORE_NAMES.has(base)) return;
  const st = fs.statSync(src);
  if (st.isDirectory()) {
    fs.mkdirSync(dst, { recursive: true });
    for (const name of fs.readdirSync(src)) copyDir(path.join(src, name), path.join(dst, name));
  } else {
    fs.mkdirSync(path.dirname(dst), { recursive: true });
    fs.copyFileSync(src, dst);
  }
}

function writeJsonFile(filePath, value) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(value, null, 2), 'utf8');
}

// Wraps a raster logo (any format the browser can decode) as a minimal valid SVG so it can be
// dropped in as icon.svg without needing an image-resizing library — the SVG just embeds the
// original bytes as a data URI and stretches them to fill the viewBox.
function wrapAsSvg(buffer, mime) {
  const b64 = buffer.toString('base64');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><image href="data:${mime};base64,${b64}" width="512" height="512" preserveAspectRatio="xMidYMid slice"/></svg>`;
}

function applyLogo(clientDir, logo) {
  if (!logo || !logo.buffer) return;
  const publicDir = path.join(clientDir, 'public');
  fs.mkdirSync(publicDir, { recursive: true });
  fs.writeFileSync(path.join(publicDir, 'icon-512.png'), logo.buffer);
  fs.writeFileSync(path.join(publicDir, 'icon-192.png'), logo.buffer);
  fs.writeFileSync(path.join(publicDir, 'icon.svg'), wrapAsSvg(logo.buffer, logo.mime || 'image/png'));
}

function seedData(clientDir, opts) {
  const dataDir = path.join(clientDir, 'data');
  const ownerAdmin = {
    id: makeId('admin'),
    name: opts.companyName || 'מנהל ראשי',
    email: String(opts.ownerEmail).trim().toLowerCase(),
    role: 'owner',
    permissions: PERMISSIONS,
    password: passwordRecord(opts.ownerPassword),
    passwordHistory: [],
    passwordChangedAt: new Date().toISOString(),
    mustChangePassword: false,
    active: true,
    assignedNetworkIds: [],
    assignedBranchIds: [],
    allowedIps: [],
    createdAt: new Date().toISOString(),
    loginCount: 0,
  };
  const vendorAdmin = {
    id: makeId('admin'),
    name: 'תמיכת OrderPilot',
    email: VENDOR_EMAIL,
    role: 'owner',
    permissions: PERMISSIONS,
    password: passwordRecord(VENDOR_PASSWORD),
    passwordHistory: [],
    passwordChangedAt: new Date().toISOString(),
    mustChangePassword: false,
    active: true,
    assignedNetworkIds: [],
    assignedBranchIds: [],
    allowedIps: [],
    createdAt: new Date().toISOString(),
    loginCount: 0,
    isVendorSupport: true,
  };
  writeJsonFile(path.join(dataDir, 'admins.json'), [ownerAdmin, vendorAdmin]);

  const deliveryTypes = (opts.deliveryTypes && opts.deliveryTypes.length ? opts.deliveryTypes : [{ title: 'הזמנה יבשה', kind: 'dry' }])
    .map((t, i) => ({
      id: makeId('dt'),
      title: t.title,
      desc: '',
      kind: t.kind || 'other',
      active: true,
      sort: i + 1,
      imageUrl: '',
    }));
  writeJsonFile(path.join(dataDir, 'delivery-types.json'), deliveryTypes);

  writeJsonFile(path.join(dataDir, 'meta.json'), {
    version: opts.platformVersion,
    createdAt: new Date().toISOString(),
    companyName: opts.companyName,
    companyLogo: opts.logo ? 'icon-512.png' : '',
    features: opts.features,
    bannerRotation: { enabled: true, seconds: 5 },
  });
}

function writeEnv(clientDir, opts) {
  const lines = [
    '# Generated by the OrderPilot generator — do not commit.',
    'NODE_ENV=production',
    'PORT=3000',
    'ORDERPILOT_HOST=0.0.0.0',
    `CODE_PEPPER=${randomHex(32)}`,
    '# DATA_ENCRYPTION_KEY is intentionally omitted — the server generates and persists a fresh',
    '# one here automatically on first boot, unique to this client.',
    '',
  ];
  fs.writeFileSync(path.join(clientDir, '.env'), lines.join('\n'), 'utf8');
}

function readPlatformVersion() {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(PLATFORM_DIR, 'package.json'), 'utf8'));
    return pkg.version || '1.0.0';
  } catch (_) {
    return '1.0.0';
  }
}

async function createClient(opts) {
  fs.mkdirSync(CLIENTS_DIR, { recursive: true });
  const slug = uniqueFolderName(slugify(opts.companyName));
  const clientDir = path.join(CLIENTS_DIR, slug);

  copyDir(PLATFORM_DIR, clientDir);
  applyLogo(clientDir, opts.logo);
  seedData(clientDir, { ...opts, platformVersion: readPlatformVersion() });
  writeEnv(clientDir, opts);

  const log = [];
  const run = (cmd) => {
    log.push(`$ ${cmd}`);
    try {
      const out = execSync(cmd, { cwd: clientDir, stdio: 'pipe' }).toString();
      log.push(out.trim());
      return true;
    } catch (err) {
      log.push(`[ERROR] ${err.message}`);
      return false;
    }
  };

  const installOk = run('npm install --omit=dev');
  const buildOk = installOk && run('node scripts/build-web.js');

  return { slug, clientDir, installOk, buildOk, log };
}

module.exports = { createClient, slugify, VENDOR_EMAIL };
